version: '3.7'
services:
  fantasy-app:
    build: ./FundamentalProject
    ports:
    - target: 8080
      published: 8080
    depends_on: 
    - mysql
  mysql:
    image: mysql
    ports:
    - target: 3306
      published: 3306
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fantasydb
    container_name: mysql
