version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
     - run: echo "Test here!"
    deploy:
      machine: 
        enabled: true
      steps:
       - run:
          name: Install Java and Maven
          command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get-install -y curl git && apt-get-install -y openjdk-8-jdk"
       - run:
          name: Clone Repo & Install Application Dependancies
          command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/Nathan2820/FundamentalProject/tree/circleci-project-setup && cd ~/FundamentalProject && sudo apt-get install -y maven"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/FundamentalProject && mvn verify"
  workflows:
    version: 2.1
    test-and-deploy:
      jobs:
        - test
        - deploy:
          requires:
            -test
          
